### ISSUE TITLE
Known bugs and todos for master (version 3.0)

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1856]
**Bugs**
 - [x] Create an activity with empty `hr_max` -> Notice *Please enter a number* appears but the tab *Upload* is shown by default, not the form where the notice appears
 - [x] opening links in a new tab (e.g. help) will result in empty pages
 - [x] _Sending the link did not work ..._ still shows up if using `user_disable_account_activation: true`
 - [x] Languages are messed up

**Todos**
 - [x] Add `.htaccess` that can enable web access in the root directory (no `/web/` in the url) [see #874]
 - [X] Remove (visual) error toolbar [see #1542]
 - [x] Document new installation requirements (chmod for `/var/`) (https://github.com/Runalyze/admin-docs/tree/3.0)
 - [x] Document all parameters of `config.yml`
 - [x] Document new update requirements (chmod for `/var/`) (https://github.com/Runalyze/admin-docs/tree/3.0)
 - [x] Document new checkout requirements (https://github.com/Runalyze/admin-docs/tree/3.0)
 - [x] Prepare tutorial in blog to update from 2.x to 3.0
 - [x] Prepare tutorial in blog to install a new 3.0
 - [x] Mechanism to switch between dev/prod environment
 - [x] `data/config.php` to some new `data/config.yml` which is loaded by `app/config/config.yml`
 - [x] Doctrine: set utc time zone
 -  [x] check if option "By clicking the register button you accept our terms of use." can be added to registration (just text for now)
 - [x] Protect installer (user can delete installer - if RUNALYZE is installed you cannot execute the installer anymore)
 - [x] Protect updater 
 - [x] Update links to update instructions in our Readme.md
 - [x] Redirect to the login page does not work when users are logged out but try to view dashboard (although this didn't work in v2.6 either)
 - [x] @mipapo script to get all translations from old and new code into *.pot file (was done manually)
 
**Wishes**
 - [x] Enable *symfony security* for user authentication
 - [x] Use twig templates for all login-related pages
 - [x] Allow admins to overwrite templates in `/data/views/...`
   - this will fix #1167, #1100, #1109
 - [x] Custom error pages
 - [X] Use Monolog instead of our Error class [see #1542]
 - [x] ~~Show warning in updater/installer if RUNALYZE does not have it's own (sub)domain~~
   - That's cleary stated in our docs.
 - [x] Remove or replace *global fix* scripts in `/build/`
   - They can be reactivated later on when providing a complete admin interface (and/or console commands). [see #1110]
 - [x] ~~Add `php-cs-fixer` + `phpmd/phpmd` to dev dependencies and use them~~
    - added to #1695
 - [x] ~~Improve error messages for login (e.g. not activated users)~~

**Untested**
 - [x] Install procedure
 - [x] Update procedure
 - [x] Funktionert das Zeitzonen raten noch ? (im migration-branch funktioniert es)
