### ISSUE TITLE
Cherry-pick bugfixes for v2.6.7

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1944]
Just for documentation. The issues themselves belong to v3.0.1 milestone.
 - [X] #1925 fix fit importer for vdot estimate
 - [X] #1935 fix vdot list in calculations window 
 - [X] #1934 fix training form for bad date input
 - [X] #1936 fix gpx importer for points without extension values
 - [X] #1928 fix avg in weekly/monthly plot
