### ISSUE TITLE
Cherry-pick bugfixes for v2.6.8

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1974]
Just for documentation. The issues themselves belong to v3.0.2 milestone.

 - [x] #1973 fix incorrect mapping of fit_recovery_time in search
 - [x] #1970 fix cleanup tool for elevation in vdot calculus 
 - [x] #1981 fix that laps window wrongly uses %HRreserve for vdot calculation
 - [x] #1861 fix vdot adjustment for elevation in laps window
 - [x] #1980 catch bad values for fit training effect
 - [x] #1991 fit import: ignore stop at beginning of activity

**Comment by laufhannes** [comment]
2.6.8 is released with 50b9b2c1c622c1cbe4007f880704222ddcb5a6fe.
